export {default as Nav} from './Nav/Nav'
export { default as Header } from './Header/Header'
export { default as Destinations } from './Destinations/Destinations'
export { default as SignIn} from './SignIn/SignIn'
export { default as LastMinute } from './LastMinute/LastMinute'
export { default as About } from './About/About'
export { default as Insurance } from './Insurance/Insurance'
export { default as Reviews } from './Reviews/Reviews'